leagueDB_app/urls.py
from django.urls import path

from . import views

app_name = 'leaguedb_app'

urlpatterns = [
    # /leaguedb_app
    path('', views.index, name='index'),
    # leaguedb_app/hello
    path('page1', views.hello, name='page1'),
    # leaguedb_app/hello/
# <<<<<<< HEAD
#     path(r'page1/(a-z)*', views.page2, name='page2'),
#
#     path('randomQuery', views.randomQuery, name='randomQuery'),
# =======
    # path(r'page1/(a-z)*', views.page2, name='page2'),

    # testing page for page2
    path('page2', views.page2, name='page2'),

    # testing page for page2
    path('page3', views.page3, name='page3'),

    # testing page for page2
    path('page4', views.page4, name='page4'),

]

league_DB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leagueDB_app/', include('leagueDB_app.urls')),
]

leagueDB_app/models.py
from django.db import models


class LeagueDBModel(models.Model):
    col = models.CharField(max_length=200)


class User(models.Model):
    uid = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=20)
    nickname = models.CharField(max_length=20, unique=True)
    publicOrNot = models.BooleanField()


class Game(models.Model):
    gid = models.IntegerField(primary_key=True)
    blueWin = models.BooleanField()
    time = models.TimeField(auto_now=True)
    gameType = models.CharField(max_length=20)


class containsRecordPerMatch(models.Model):
    sid = models.IntegerField(primary_key=True)
    gid = models.IntegerField(unique=True)
    uid = models.IntegerField(unique=True)
    gid = models.ForeignKey(Game, on_delete=models.CASCADE)
    uid = models.ForeignKey(User, on_delete=models.CASCADE)


class Champion(models.Model):
    cid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20)
    melee = models.BooleanField()


class asRecordPerMatch(models.Model):
    sid = models.IntegerField()
    cid = models.IntegerField()
    gold = models.IntegerField()
    kill = models.IntegerField()
    death = models.IntegerField()
    damage = models.IntegerField()
    damageTaken = models.IntegerField()
    cs = models.IntegerField()
    level = models.IntegerField()
    teamBlue = models.BooleanField()
    cid = models.ForeignKey(Champion, on_delete=models.CASCADE)


class Master(models.Model):
    cid = models.IntegerField(primary_key=True)
    uid = models.IntegerField(unique=True)
    point = models.IntegerField()
    cid = models.ForeignKey(Champion, on_delete=models.CASCADE)
    uid = models.ForeignKey(User, related_name='user_id', on_delete=models.CASCADE)


class Item(models.Model):
    iid = models.IntegerField(primary_key=True)
    itemName = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=80, null=True)
    gold = models.IntegerField()


class Recommend(models.Model):
    cid = models.IntegerField(primary_key=True)
    iid = models.IntegerField(unique=True)
    cid = models.ForeignKey(Champion, on_delete=models.CASCADE)
    iid = models.ForeignKey(Item, on_delete=models.CASCADE)


class Object(models.Model):
    oid = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=80, null=True)


class buyEvent(models.Model):
    eid = models.IntegerField(primary_key=True)
    iid = models.IntegerField(unique=True)
    time = models.TimeField(auto_now=True)
    iid = models.ForeignKey(Item, on_delete=models.CASCADE)


class didBuyEvent(models.Model):
    eid = models.IntegerField(primary_key=True)
    sid = models.IntegerField(unique=True)
    time = models.TimeField(auto_now=True)
    sid = models.ForeignKey(asRecordPerMatch, on_delete=models.CASCADE)


class getObjectEvent(models.Model):
    eid = models.IntegerField(primary_key=True)
    oid = models.IntegerField(unique=True)
    time = models.TimeField(auto_now=True)
    oid = models.ForeignKey(Object, on_delete=models.CASCADE)


class didObjectEvent(models.Model):
    eid = models.IntegerField(primary_key=True)
    sid = models.IntegerField(unique=True)
    time = models.TimeField(auto_now=True)
    sid = models.ForeignKey(asRecordPerMatch, on_delete=models.CASCADE)


class didKillEvent(models.Model):
    eid = models.IntegerField(primary_key=True)
    time = models.TimeField(auto_now=True)
    killerSid = models.IntegerField()
    victimSid = models.IntegerField(unique=True)
    victimSid = models.ForeignKey(asRecordPerMatch, on_delete=models.CASCADE)

leagueDB_app/views.py
from django.shortcuts import render
from django.http import HttpResponse 
from django.template import loader
from .models import LeagueDBModel


def index(request):
    return HttpResponse('Reached LeagueDB_app')


def hello(request):
    leagueList = LeagueDBModel.objects.raw('SELECT id, col from "leagueDB_app_leaguedbmodel"')
    template = loader.get_template('leagueDB_app/index.html')
    context = {
        'latest_question_list': leagueList,
    }
    return HttpResponse(template.render(context, request))



# Those None need to be replaced by SQL
def page2(request):
    # for page 2 username is the parameter passed from URL
    username = request.content_params.get('username')
    top5_champions = LeagueDBModel.objects.raw('SELECT cid AS id, name FROM "leagueDB_app_champion"')

    matches = LeagueDBModel.objects.raw('SELECT name from "leagueDB_app_champion"')

    context = {
        'top5': top5_champions,
        'matches': matches
    }
    template = loader.get_template('leagueDB_app/page2.html')
    return HttpResponse(template.render(context, request))


def page3(request):

    champions_name = LeagueDBModel.objects.raw('SELECT cid AS id, name FROM "leagueDB_app_champion"')
    winrate_with_champion_name = None
    context = {
        'champ_name': champions_name,
        'winrate': winrate_with_champion_name
    }
    template = loader.get_template('leagueDB_app/page3.html')
    return HttpResponse(template.render(context, request))


def page4(request):
    # for page 4, champion name is the parameter passed from URL
    champion_name = request.content_params.get('champion_name')
    top5_player = None
    recommond_items = None
    context = {
        'top5': top5_player,
        'recom': recommond_items
    }

    template = loader.get_template('leagueDB_app/page4.html')
    return HttpResponse(template.render(context, request))

# Create your views here.

leagueDB_app/templates/leagueDB_app/index.html
{% load static %}
<title>LeagueDB</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
    <div class="header-text">LeagueDB</div>
</header>

<!-- {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/leagueDB_app/ col.id }}/">{{ question.col }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

<section class="landing-section landing-main">
    <div class="landing-section-content">
        <h1 class="brand">Champion Analysis</h1>
        <h2>
            <span class="brand-text">
                {% if error_message %}
                {{error_message}}
                {% endif %}</span>
            <form action="{% url 'leaguedb_app:page1'%}" method="post">
                {% csrf_token %}
                <input type="form" id="testName" name="name" />
                <input type="submit">
            </form>
            <span class="brand-text">Database</span>
        </h2>

    </div>
</section>


<style>
    .header {
        width: 100vw;
        display: flex;
        justify-content: flex-end;
        top: 0;
        left: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
    }
    
    .header-text {
        margin: 1rem;
        font-size: 70px;
        color: #ccc;
    }
    
    .landing-section {
        min-height: 60vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }
    
    .landing-section-content {
        padding: 2rem;
        background: rgba(0, 0, 0, 0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
    }
    
    .brand {
        margin: 0;
        color: #0035c5;
    }
    
    .brand-text {
        color: #0035c5;
    }
</style>

leagueDB_app/templates/leagueDB_app/page2.html
{% load static %}
<title>LeagueDB</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
    <div class="header-text">LeagueDB</div>
</header>

<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><span style="font-size: 20pt;">Username: TestName</span></p>
<p><span style="font-size: 15pt;">Top 5 Champions:</span></p>
{#Add for loop for top 5 champions#}
<tbody>
    {% for c in top5 %}
        <tr>
            <td>{{ c.name }}</td>
        </tr>
    {% endfor %}

</tbody>
<p><span style="font-size: 15pt;">Matches:</span></p>
{#Add for loop for matches#}
    {% for url in top5 %}
        <tr>
            <td>{{ url.name }}</td>
        </tr>
    {% endfor %}
</body>





<!-- {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/leagueDB_app/ col.id }}/">{{ question.col }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

{#<section class="landing-section landing-main">#}
{#    <div class="landing-section-content">#}
{#        <h1 class="brand">Champion Analysis</h1>#}
{#        <h2>#}
{#            <span class="brand-text">#}
{#                {% if error_message %}#}
{#                {{error_message}}#}
{#                {% endif %}</span>#}
{#            <form action="{% url 'leaguedb_app:page2'%}" method="post">#}
{#                {% csrf_token %}#}
{#                <input type="form" id="testName" name="name" />#}
{#                <input type="submit">#}
{#            </form>#}
{#            <span class="brand-text">Database</span>#}
{#        </h2>#}
{##}
{#    </div>#}
{#</section>#}


<style>
    .header {
        width: 100vw;
        display: flex;
        justify-content: flex-end;
        top: 0;
        left: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
    }

    .header-text {
        margin: 1rem;
        font-size: 70px;
        color: #ccc;
    }

    .landing-section {
        min-height: 60vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .landing-section-content {
        padding: 2rem;
        background: rgba(0, 0, 0, 0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
    }

    .brand {
        margin: 0;
        color: #0035c5;
    }

    .brand-text {
        color: #0035c5;
    }
</style>

leagueDB_app/templates/leagueDB_app/page3.html
{% load static %}
<title>LeagueDB</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
    <div class="header-text">LeagueDB</div>
</header>

<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><span style="font-size: 20pt;">Champion list</span></p>
<p><span style="font-size: 15pt;">Champions:</span></p>
{#Add for loop for top 5 champions#}
<tbody>
    {% for c in champ_name %}
        <tr>
            <td>{{ c.name }}</td>
        </tr>
    {% endfor %}

</tbody>
<p><span style="font-size: 15pt;">Win rate:</span></p>
{#Add for loop for matches#}
</body>





<!-- {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/leagueDB_app/ col.id }}/">{{ question.col }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

{#<section class="landing-section landing-main">#}
{#    <div class="landing-section-content">#}
{#        <h1 class="brand">Champion Analysis</h1>#}
{#        <h2>#}
{#            <span class="brand-text">#}
{#                {% if error_message %}#}
{#                {{error_message}}#}
{#                {% endif %}</span>#}
{#            <form action="{% url 'leaguedb_app:page2'%}" method="post">#}
{#                {% csrf_token %}#}
{#                <input type="form" id="testName" name="name" />#}
{#                <input type="submit">#}
{#            </form>#}
{#            <span class="brand-text">Database</span>#}
{#        </h2>#}
{##}
{#    </div>#}
{#</section>#}


<style>
    .header {
        width: 100vw;
        display: flex;
        justify-content: flex-end;
        top: 0;
        left: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
    }

    .header-text {
        margin: 1rem;
        font-size: 70px;
        color: #ccc;
    }

    .landing-section {
        min-height: 60vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .landing-section-content {
        padding: 2rem;
        background: rgba(0, 0, 0, 0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
    }

    .brand {
        margin: 0;
        color: #0035c5;
    }

    .brand-text {
        color: #0035c5;
    }
</style>

leagueDB_app/templates/leagueDB_app/page4.html
{% load static %}
<title>LeagueDB</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
    <div class="header-text">LeagueDB</div>
</header>

<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><span style="font-size: 20pt;">Champion Name: TestName</span></p>
<p><span style="font-size: 15pt;">Top 5 player:</span></p>
{#Add for loop for top 5 champions#}
<p><span style="font-size: 15pt;">Items recommendation:</span></p>
{#Add for loop for matches#}
</body>





<!-- {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/leagueDB_app/ col.id }}/">{{ question.col }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

{#<section class="landing-section landing-main">#}
{#    <div class="landing-section-content">#}
{#        <h1 class="brand">Champion Analysis</h1>#}
{#        <h2>#}
{#            <span class="brand-text">#}
{#                {% if error_message %}#}
{#                {{error_message}}#}
{#                {% endif %}</span>#}
{#            <form action="{% url 'leaguedb_app:page2'%}" method="post">#}
{#                {% csrf_token %}#}
{#                <input type="form" id="testName" name="name" />#}
{#                <input type="submit">#}
{#            </form>#}
{#            <span class="brand-text">Database</span>#}
{#        </h2>#}
{##}
{#    </div>#}
{#</section>#}


<style>
    .header {
        width: 100vw;
        display: flex;
        justify-content: flex-end;
        top: 0;
        left: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
    }

    .header-text {
        margin: 1rem;
        font-size: 70px;
        color: #ccc;
    }

    .landing-section {
        min-height: 60vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .landing-section-content {
        padding: 2rem;
        background: rgba(0, 0, 0, 0.5);
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
    }

    .brand {
        margin: 0;
        color: #0035c5;
    }

    .brand-text {
        color: #0035c5;
    }
</style>

leagueDB_app/templates/randomQuery/index.html
{% load static %}
<title>LeagueDB</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<header class="header">
    <div class="header-text">LeagueDB</div>
</header>



<section class="landing-section landing-main">
    <div class="landing-section-content">
        <h1 class="brand">Champion Analysis</h1>
        <h2>
            <span class="brand-text">
                {% if error_message %}
                {{error_message}}
                {% endif %}</span>
            <form action="{% url 'leaguedb_app:page1' %}" method="post">
                {% csrf_token %}
                <input type="form" id="testName" name="name" />
                <input type="submit">
            </form>
        </h2>

    </div>
</section>

<section class="query-section">
    <div>
        <form action='randomQuery' method='GET'>
            <button type='submit'>Random Query</button>
        </form>
        {% if randomQueryList %}
        <ul>
            {% for query in randomQueryList %}
            <li>{{ query.gameType }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}

    </div>

</section>


<section class="landing-section langing-features">
    <section class="landing-feature feature-music-services">
        <h2>Connect your favourite <span class="brand-text">mu</span>sic services</h2>
        <ul>
            <li>Spotify</li>
            <li>Deezer</li>
        </ul>
    </section>
    <section class="landing-feature feature-notifications">
        <h2>Get <span class="brand-text">n</span>otifications wherever you want them</h2>
        <ul>
            <li>Email</li>
            <li>Telegram</li>
        </ul>
    </section>
</section>

<style>
    .header {
        width: 100vw;
        display: flex;
        justify-content: flex-end;
        top: 0;
        left: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
    }
    
    .header-text {
        margin: 1rem;
        font-size: 70px;
        color: #ccc;
    }
    
    .landing-section {
        min-height: 60vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }
    
    .landing-section-content {
        padding: 2rem;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        color: #ccc;
    }
    
    .brand {
        margin: 0;
        color: #0035c5;
    }
    
    .brand-text {
        color: #0035c5;
    }
</style>